spring.application.name=EasyBasket

EasyBasket.country=india
EasyBasket.enable=true
EasyBasket.listOfValues=aaa,bbbb,ccccc
EasyBasket.aiModel=gemini

spring.security.user.name=admin
spring.security.user.password=admin123